In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [193]:
!ls -lath data

total 102280
drwxr-xr-x  7 DAILYSPARK  staff   224B Jan  6 20:24 ..
drwxr-xr-x  6 DAILYSPARK  staff   192B Jan  6 19:42 .
-rw-r--r--@ 1 DAILYSPARK  staff   3.6M Jan  6 19:38 Hospitals.csv
-rw-r--r--@ 1 DAILYSPARK  staff   227K Jan  6 16:27 CountyCrossWalk_Zillow.csv
-rw-r--r--@ 1 DAILYSPARK  staff    42M Jan  6 15:20 Public_Schools.csv
-rw-r--r--@ 1 DAILYSPARK  staff   3.6M Jan  5 17:22 County_Zhvi_AllHomes.csv

In [16]:
df = pd.read_csv('data/County_Zhvi_AllHomes.csv', encoding='latin1')

In [25]:
display(df.describe())
df.info()
df.head()

,RegionID,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2008-01,2008-02,2008-03,2008-04,2008-05,2008-06,...,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
count,2018.000000,2018.000000,2018.000000,2018.000000,1.675000e+03,1.717000e+03,1.725000e+03,1.729000e+03,1.738000e+03,1.743000e+03,...,2.018000e+03,2.018000e+03,2.018000e+03,2.018000e+03,2.018000e+03,2.018000e+03,2.018000e+03,2.018000e+03,2.018000e+03,2.018000e+03
mean,2067.587711,30.411794,100.245292,1009.500000,1.620621e+05,1.623351e+05,1.622051e+05,1.616362e+05,1.609879e+05,1.601282e+05,...,1.877864e+05,1.884452e+05,1.891131e+05,1.897811e+05,1.904129e+05,1.910132e+05,1.916043e+05,1.922238e+05,1.928333e+05,1.932455e+05
std,15543.872219,15.111202,109.281186,582.690741,9.998748e+04,1.001488e+05,9.986633e+04,9.916502e+04,9.834161e+04,9.744337e+04,...,1.247496e+05,1.248964e+05,1.250613e+05,1.252512e+05,1.253754e+05,1.254423e+05,1.254534e+05,1.255843e+05,1.257414e+05,1.258760e+05
min,66.000000,1.000000,1.000000,1.000000,3.380900e+04,3.379950e+04,3.387533e+04,3.412367e+04,3.440100e+04,3.466267e+04,...,4.401933e+04,4.421600e+04,4.436133e+04,4.452200e+04,4.472167e+04,4.469167e+04,4.478333e+04,4.462967e+04,4.480967e+04,4.457100e+04
25%,913.250000,18.000000,33.000000,505.250000,9.877000e+04,9.868700e+04,9.882800e+04,9.854700e+04,9.825725e+04,9.808400e+04,...,1.133656e+05,1.139274e+05,1.142568e+05,1.150439e+05,1.152840e+05,1.158925e+05,1.163178e+05,1.170755e+05,1.174827e+05,1.176804e+05
50%,1732.000000,29.000000,75.000000,1009.500000,1.351110e+05,1.352945e+05,1.352797e+05,1.350117e+05,1.346587e+05,1.339927e+05,...,1.560745e+05,1.567922e+05,1.575453e+05,1.584327e+05,1.588497e+05,1.595802e+05,1.602148e+05,1.609615e+05,1.616097e+05,1.616860e+05
75%,2556.750000,45.000000,129.000000,1513.750000,1.933215e+05,1.939580e+05,1.943587e+05,1.940010e+05,1.927654e+05,1.922127e+05,...,2.212929e+05,2.219506e+05,2.227452e+05,2.237943e+05,2.248783e+05,2.256547e+05,2.265561e+05,2.272890e+05,2.274881e+05,2.281344e+05
max,698720.000000,56.000000,840.000000,2018.000000,1.181295e+06,1.184977e+06,1.176099e+06,1.171844e+06,1.165266e+06,1.164527e+06,...,1.582678e+06,1.588063e+06,1.591903e+06,1.595350e+06,1.601888e+06,1.607942e+06,1.615246e+06,1.621570e+06,1.629556e+06,1.631982e+06

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2018 entries, 0 to 2017
Columns: 150 entries, RegionID to 2019-11
dtypes: float64(143), int64(4), object(3)
memory usage: 2.3+ MB

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2008-01,2008-02,2008-03,...,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
0,3101,Los Angeles County,CA,Los Angeles-Long Beach-Anaheim,6,37,1,NaN,NaN,472143.000000,...,627605.333333,626330.000000,626452.666667,627361.333333,629635.333333,627320.000000,626593.333333,627129.666667,631862.000000,635059.000000
1,139,Cook County,IL,Chicago-Naperville-Elgin,17,31,2,NaN,NaN,NaN,...,242852.333333,243802.000000,244960.000000,245683.000000,245542.333333,244876.333333,243834.333333,242881.000000,242228.000000,242093.000000
2,1090,Harris County,TX,Houston-The Woodlands-Sugar Land,48,201,3,141119.0,140846.0,140670.666667,...,195453.666667,195767.000000,195631.333333,195685.333333,196198.000000,196728.333333,197370.333333,197644.000000,198527.333333,199147.000000
3,2402,Maricopa County,AZ,Phoenix-Mesa-Scottsdale,4,13,4,NaN,227053.0,224923.000000,...,279281.333333,280771.666667,281602.333333,282539.666667,283581.666667,285116.666667,287170.666667,288931.333333,290680.666667,292223.666667
4,2841,San Diego County,CA,San Diego-Carlsbad,6,73,5,436525.0,432364.0,428459.000000,...,587666.333333,587108.000000,589288.666667,590122.000000,592045.000000,594354.000000,596542.333333,597062.333333,598175.000000,600560.000000

In [252]:
# for c in df.columns: print(c)

In [221]:
# Filter down to the month we plan to use, June 2019

df_Jun2019 = df[['RegionID', 'RegionName', 'State', 'Metro', 'StateCodeFIPS', 'MunicipalCodeFIPS', 'SizeRank', '2019-06']]
df_Jun2019

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2019-06
0,3101,Los Angeles County,CA,Los Angeles-Long Beach-Anaheim,6,37,1,629635.333333
1,139,Cook County,IL,Chicago-Naperville-Elgin,17,31,2,245542.333333
2,1090,Harris County,TX,Houston-The Woodlands-Sugar Land,48,201,3,196198.000000
3,2402,Maricopa County,AZ,Phoenix-Mesa-Scottsdale,4,13,4,283581.666667
4,2841,San Diego County,CA,San Diego-Carlsbad,6,73,5,592045.000000
...,...,...,...,...,...,...,...,...
2013,1793,Jackson County,CO,NaN,8,57,2014,174656.000000
2014,1648,Daggett County,UT,NaN,49,9,2015,207925.666667
2015,2345,Hinsdale County,CO,NaN,8,53,2016,329117.333333
2016,1933,Mineral County,CO,NaN,8,79,2017,263305.333333
2017,2518,San Juan County,CO,NaN,8,111,2018,285736.666667

In [222]:
df_va = df_Jun2019.loc[df_Jun2019['State'] == 'VA']

In [223]:
df_va['RegionName'].unique()

array(['Fairfax County', 'Virginia Beach City', 'Prince William County',
       'Chesterfield County', 'Loudoun County', 'Henrico County',
       'Norfolk City', 'Chesapeake City', 'Arlington County',
       'Richmond City', 'Newport News City', 'Alexandria City',
       'Hampton City', 'Stafford County', 'Spotsylvania County',
       'Hanover County', 'Albemarle County', 'Roanoke City',
       'Portsmouth City', 'Montgomery County', 'Roanoke County',
       'Suffolk City', 'Frederick County', 'Rockingham County',
       'Lynchburg City', 'Augusta County', 'Bedford County',
       'James City County', 'York County', 'Fauquier County',
       'Pittsylvania County', 'Franklin County', 'Washington County',
       'Campbell County', 'Henry County', 'Harrisonburg City',
       'Culpeper County', 'Charlottesville City', 'Shenandoah County',
       'Wise County', 'Manassas City', 'Warren County',
       'Gloucester County', 'Halifax County', 'Prince George County',
       'Isle of Wight County', 'Pulaski County', 'Orange County',
       'Louisa County', 'Botetourt County', 'Petersburg City',
       'Amherst County', 'Smyth County', 'Caroline County',
       'Powhatan County', 'Dinwiddie County', 'Winchester City',
       'Fluvanna County', 'Salem City', 'Fredericksburg City',
       'Buchanan County', 'Page County', 'Staunton City',
       'King George County', 'Prince Edward County', 'Scott County',
       'Hopewell City', 'Fairfax City', 'Rockbridge County',
       'Goochland County', 'Waynesboro City', 'New Kent County',
       'Greene County', 'Bristol City', 'Westmoreland County',
       'Colonial Heights City', 'Alleghany County', 'King William County',
       'Grayson County', 'Nelson County', 'Williamsburg City',
       'Clarke County', 'Madison County', 'Falls Church City',
       'Poquoson City', 'Sussex County', 'Lancaster County',
       'Essex County', 'Middlesex County', 'Galax City'], dtype=object)

In [224]:
nova_counties = ['Alexandria City', 'Arlington County', 'Clarke County', 'Culpeper County', 'Fairfax City', 'Fairfax County', 'Falls Church City',
                 'Fauquier County', 'Frederick County', 'Fredericksburg City', 'Loudoun County', 'Madison County', 'Manassas City', 'Manassas Park City', 
                 'Prince William County', 'Rappahannock County', 'Spotsylvania County', 'Stafford County', 'Warren County', 'Winchester City']
len(nova_counties)

20

In [225]:
df_nova = df_va.loc[df_va['RegionName'].isin(nova_counties)]
df_nova

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2019-06
35,1694,Fairfax County,VA,Washington-Arlington-Alexandria,51,59,36,558783.000000
164,3247,Prince William County,VA,Washington-Arlington-Alexandria,51,153,165,385136.000000
202,1887,Loudoun County,VA,Washington-Arlington-Alexandria,51,107,203,531570.333333
293,2619,Arlington County,VA,Washington-Arlington-Alexandria,51,13,294,711743.333333
427,3253,Alexandria City,VA,Washington-Arlington-Alexandria,51,510,428,554203.000000
466,2556,Stafford County,VA,Washington-Arlington-Alexandria,51,179,467,347158.333333
481,3193,Spotsylvania County,VA,Washington-Arlington-Alexandria,51,177,482,287085.666667
662,2700,Frederick County,VA,Winchester,51,69,663,267555.000000
761,2261,Fauquier County,VA,Washington-Arlington-Alexandria,51,61,762,419933.666667
961,2240,Culpeper County,VA,Washington-Arlington-Alexandria,51,47,962,293808.000000
1124,3213,Manassas City,VA,Washington-Arlington-Alexandria,51,683,1125,330914.333333
1131,1483,Warren County,VA,Washington-Arlington-Alexandria,51,187,1132,223468.333333
1383,3263,Winchester City,VA,Winchester,51,840,1384,213703.000000
1444,3283,Fredericksburg City,VA,Washington-Arlington-Alexandria,51,630,1445,325345.333333
1498,3162,Fairfax City,VA,Washington-Arlington-Alexandria,51,600,1499,544894.000000
1775,943,Clarke County,VA,Washington-Arlington-Alexandria,51,43,1776,358250.000000
1804,1913,Madison County,VA,NaN,51,113,1805,226508.666667
1827,3272,Falls Church City,VA,Washington-Arlington-Alexandria,51,610,1828,812208.666667

In [226]:
set(nova_counties) - set(df_va['RegionName'].unique())

{'Manassas Park City', 'Rappahannock County'}

In [253]:
df_dcmetro = df_Jun2019.loc[df_Jun2019['Metro'] == 'Washington-Arlington-Alexandria']
df_dcmetro

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2019-06
35,1694,Fairfax County,VA,Washington-Arlington-Alexandria,51,59,36,558783.000000
41,2975,Montgomery County,MD,Washington-Arlington-Alexandria,24,31,42,470224.666667
58,3246,Prince Georges County,MD,Washington-Arlington-Alexandria,24,33,59,312947.333333
104,3289,District of Columbia,DC,Washington-Arlington-Alexandria,11,1,105,623966.666667
164,3247,Prince William County,VA,Washington-Arlington-Alexandria,51,153,165,385136.000000
202,1887,Loudoun County,VA,Washington-Arlington-Alexandria,51,107,203,531570.333333
270,2699,Frederick County,MD,Washington-Arlington-Alexandria,24,21,271,337613.000000
293,2619,Arlington County,VA,Washington-Arlington-Alexandria,51,13,294,711743.333333
414,1607,Charles County,MD,Washington-Arlington-Alexandria,24,17,415,310631.000000
427,3253,Alexandria City,VA,Washington-Arlington-Alexandria,51,510,428,554203.000000
466,2556,Stafford County,VA,Washington-Arlington-Alexandria,51,179,467,347158.333333
481,3193,Spotsylvania County,VA,Washington-Arlington-Alexandria,51,177,482,287085.666667
618,1581,Calvert County,MD,Washington-Arlington-Alexandria,24,9,619,341216.666667
761,2261,Fauquier County,VA,Washington-Arlington-Alexandria,51,61,762,419933.666667
870,2757,Jefferson County,WV,Washington-Arlington-Alexandria,54,37,871,228683.666667
961,2240,Culpeper County,VA,Washington-Arlington-Alexandria,51,47,962,293808.000000
1124,3213,Manassas City,VA,Washington-Arlington-Alexandria,51,683,1125,330914.333333
1131,1483,Warren County,VA,Washington-Arlington-Alexandria,51,187,1132,223468.333333
1444,3283,Fredericksburg City,VA,Washington-Arlington-Alexandria,51,630,1445,325345.333333
1498,3162,Fairfax City,VA,Washington-Arlington-Alexandria,51,600,1499,544894.000000
1775,943,Clarke County,VA,Washington-Arlington-Alexandria,51,43,1776,358250.000000
1827,3272,Falls Church City,VA,Washington-Arlington-Alexandria,51,610,1828,812208.666667

In [254]:
# Use to create dictionary for CountyName : CountyFIPS

{ a: None for a in sorted(list(df_dcmetro['RegionName']))}

{'Alexandria City': None,
 'Arlington County': None,
 'Calvert County': None,
 'Charles County': None,
 'Clarke County': None,
 'Culpeper County': None,
 'District of Columbia': None,
 'Fairfax City': None,
 'Fairfax County': None,
 'Falls Church City': None,
 'Fauquier County': None,
 'Frederick County': None,
 'Fredericksburg City': None,
 'Jefferson County': None,
 'Loudoun County': None,
 'Manassas City': None,
 'Montgomery County': None,
 'Prince Georges County': None,
 'Prince William County': None,
 'Spotsylvania County': None,
 'Stafford County': None,
 'Warren County': None}

In [255]:
dcmetro_FIPS = {
 'Alexandria City': 51510,
 'Arlington County': 51013,
 'Calvert County': 24009,
 'Charles County': 24017,
 'Clarke County': 51043,
 'Culpeper County': 51047,
 'District of Columbia': 11001,
 'Fairfax City': 51600,
 'Fairfax County': 51059,
 'Falls Church City': 51610,
 'Fauquier County': 51061,
 'Frederick County': 24021,
 'Fredericksburg City': 51630,
 'Jefferson County': 54037,
 'Loudoun County': 51107,
 'Manassas City': 51683,
 'Montgomery County': 24031,
 'Prince Georges County': 24033,
 'Prince William County': 51153,
 'Spotsylvania County': 51177,
 'Stafford County': 51179,
 'Warren County': 51187
}

In [256]:
df_dcmetro['FIPS'] = df_dcmetro['RegionName'].map(dcmetro_FIPS)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [257]:
df_dcmetro

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2019-06,FIPS
35,1694,Fairfax County,VA,Washington-Arlington-Alexandria,51,59,36,558783.000000,51059
41,2975,Montgomery County,MD,Washington-Arlington-Alexandria,24,31,42,470224.666667,24031
58,3246,Prince Georges County,MD,Washington-Arlington-Alexandria,24,33,59,312947.333333,24033
104,3289,District of Columbia,DC,Washington-Arlington-Alexandria,11,1,105,623966.666667,11001
164,3247,Prince William County,VA,Washington-Arlington-Alexandria,51,153,165,385136.000000,51153
202,1887,Loudoun County,VA,Washington-Arlington-Alexandria,51,107,203,531570.333333,51107
270,2699,Frederick County,MD,Washington-Arlington-Alexandria,24,21,271,337613.000000,24021
293,2619,Arlington County,VA,Washington-Arlington-Alexandria,51,13,294,711743.333333,51013
414,1607,Charles County,MD,Washington-Arlington-Alexandria,24,17,415,310631.000000,24017
427,3253,Alexandria City,VA,Washington-Arlington-Alexandria,51,510,428,554203.000000,51510
466,2556,Stafford County,VA,Washington-Arlington-Alexandria,51,179,467,347158.333333,51179
481,3193,Spotsylvania County,VA,Washington-Arlington-Alexandria,51,177,482,287085.666667,51177
618,1581,Calvert County,MD,Washington-Arlington-Alexandria,24,9,619,341216.666667,24009
761,2261,Fauquier County,VA,Washington-Arlington-Alexandria,51,61,762,419933.666667,51061
870,2757,Jefferson County,WV,Washington-Arlington-Alexandria,54,37,871,228683.666667,54037
961,2240,Culpeper County,VA,Washington-Arlington-Alexandria,51,47,962,293808.000000,51047
1124,3213,Manassas City,VA,Washington-Arlington-Alexandria,51,683,1125,330914.333333,51683
1131,1483,Warren County,VA,Washington-Arlington-Alexandria,51,187,1132,223468.333333,51187
1444,3283,Fredericksburg City,VA,Washington-Arlington-Alexandria,51,630,1445,325345.333333,51630
1498,3162,Fairfax City,VA,Washington-Arlington-Alexandria,51,600,1499,544894.000000,51600
1775,943,Clarke County,VA,Washington-Arlington-Alexandria,51,43,1776,358250.000000,51043
1827,3272,Falls Church City,VA,Washington-Arlington-Alexandria,51,610,1828,812208.666667,51610

In [258]:
df_schools = pd.read_csv('data/Public_Schools.csv')
df_schools.head()

,X,Y,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,ST_GRADE,END_GRADE,DISTRICTID,FT_TEACHER,SHELTER_ID
0,-73.534274,41.327100,1,90381001361,SCOTTS RIDGE MIDDLE SCHOOL,750 NORTH SALEM RD.,RIDGEFIELD,CT,6877,NOT AVAILABLE,...,IMAGERY,2010-03-05T00:00:00.000Z,www.ridgefield.org/srms/index.htm,2,496,06,08,903810,42,10807677
1,-83.002954,42.609035,2,263447007003,BEMIS JUNIOR HIGH SCHOOL,12500 19 MILE RD,STERLING HEIGHTS,MI,48313,2682,...,IMAGERY,2010-08-26T00:00:00.000Z,NOT AVAILABLE,2,943,07,09,2634470,44,NOT AVAILABLE
2,-119.784787,39.509917,3,320048000242,ROGER CORBETT ELEMENTARY SCHOOL,1901 VILLANOVA DRIVE,RENO,NV,89502,NOT AVAILABLE,...,IMAGERY,2010-06-01T00:00:00.000Z,NOT AVAILABLE,1,515,PK,06,3200480,32,NOT AVAILABLE
3,-98.472562,29.436838,4,483312007184,NISD BEXAR COUNTY JJA,1402 HACKBERRY,SAN ANTONIO,TX,78238,1699,...,IMAGERY,2010-02-25T00:00:00.000Z,NOT AVAILABLE,4,25,06,12,4833120,-1,NOT AVAILABLE
4,-95.491060,29.596903,5,481965001816,BRIARGATE EL,15817 BLUE RIDGE RD,MISSOURI CITY,TX,77489,3403,...,IMAGERY,2010-06-21T00:00:00.000Z,www.fortbend.k12.tx.us/campuses/bge/default.cfm,1,468,PK,05,4819650,30,NOT AVAILABLE

In [259]:
df_schools.columns

Index(['X', 'Y', 'OBJECTID', 'NCESID', 'NAME', 'ADDRESS', 'CITY', 'STATE',
       'ZIP', 'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY',
       'COUNTYFIPS', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE',
       'WEBSITE', 'LEVEL_', 'ENROLLMENT', 'ST_GRADE', 'END_GRADE',
       'DISTRICTID', 'FT_TEACHER', 'SHELTER_ID'],
      dtype='object')

In [260]:
df_schools['COUNTYFIPS'].value_counts()

6037     2301
17031    1317
4013     1252
48201    1142
6073      768
         ...
13263       1
48155       1
13007       1
31009       1
48269       1
Name: COUNTYFIPS, Length: 3223, dtype: int64

In [261]:
df_schools['COUNTYFIPS'].value_counts().to_frame()

       COUNTYFIPS
6037         2301
17031        1317
4013         1252
48201        1142
6073          768
...           ...
13263           1
48155           1
13007           1
31009           1
48269           1

[3223 rows x 1 columns]

In [262]:
df_schools_brief = df_public_schools[['NAME', 'CITY', 'STATE', 'ZIP','COUNTY','COUNTYFIPS', 'DISTRICTID']]
df_schools_brief.head()

,NAME,CITY,STATE,ZIP,COUNTY,COUNTYFIPS,DISTRICTID
0,SCOTTS RIDGE MIDDLE SCHOOL,RIDGEFIELD,CT,6877,FAIRFIELD,9001,903810
1,BEMIS JUNIOR HIGH SCHOOL,STERLING HEIGHTS,MI,48313,MACOMB,26099,2634470
2,ROGER CORBETT ELEMENTARY SCHOOL,RENO,NV,89502,WASHOE,32031,3200480
3,NISD BEXAR COUNTY JJA,SAN ANTONIO,TX,78238,BEXAR,48029,4833120
4,BRIARGATE EL,MISSOURI CITY,TX,77489,FORT BEND,48157,4819650

In [263]:
schools_per_county = df_schools['COUNTYFIPS'].value_counts().to_frame()
schools_per_county.reset_index(level=0, inplace=True)
schools_per_county.rename(index=str, columns={"index": "FIPS", "COUNTYFIPS": "NumberOfSchools"}, inplace=True)
schools_per_county.shape

(3223, 2)

In [264]:
schools_per_county_dcmetro = schools_per_county.loc[schools_per_county['FIPS'].isin(dcmetro_FIPS.values())]

In [265]:
schools_per_county_dcmetro.shape

(22, 2)

In [266]:
df_hospitals = pd.read_csv('data/Hospitals.csv')
df_hospitals.head()

,X,Y,OBJECTID,ID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_DATE,WEBSITE,STATE_ID,ALT_NAME,ST_FIPS,OWNER,TTL_STAFF,BEDS,TRAUMA,HELIPAD
0,-83.387732,39.348667,3001,12645123,ADENA GREENFIELD MEDICAL CENTER,550 MIRABEAU STREET,GREENFIELD,OH,45123,NOT AVAILABLE,...,2014-02-10T00:00:00.000Z,http://www.adena.org/locations/detail.dT/adena...,1200,NOT AVAILABLE,39,NON-PROFIT,-999,25,NOT AVAILABLE,N
1,-81.919907,40.565095,3002,17244654,POMERENE HOSPITAL,981 WOOSTER ROAD,MILLERSBURG,OH,44654,NOT AVAILABLE,...,2014-01-31T00:00:00.000Z,http://www.pomerenehospital.org,1202,NOT AVAILABLE,39,GOVERNMENT - LOCAL,-999,69,NOT AVAILABLE,N
2,-82.450635,40.048302,3003,2543055,LICKING MEMORIAL HOSPITAL,1320 WEST MAIN STREET,NEWARK,OH,43055,NOT AVAILABLE,...,2014-02-10T00:00:00.000Z,http://www.lmhealth.org,1213,NOT AVAILABLE,39,NON-PROFIT,-999,213,NOT AVAILABLE,Y
3,-83.755531,40.369542,3004,5843311,MARY RUTAN HOSPITAL,205 PALMER AVENUE,BELLEFONTAINE,OH,43311,NOT AVAILABLE,...,2014-02-10T00:00:00.000Z,http://www.maryrutan.org,1214,NOT AVAILABLE,39,NON-PROFIT,-999,115,NOT AVAILABLE,N
4,-82.224713,41.295065,3005,5544074,MERCY ALLEN HOSPITAL,200 WEST LORAIN STREET,OBERLIN,OH,44074,NOT AVAILABLE,...,2014-02-10T00:00:00.000Z,http://www.mercyonline.org/mercy_allen_hospita...,1219,ALLEN COMMUNITY HOSPITAL,39,NON-PROFIT,-999,25,NOT AVAILABLE,Y

In [267]:
df_hospitals.columns

Index(['X', 'Y', 'OBJECTID', 'ID', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP',
       'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY',
       'COUNTYFIPS', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE',
       'WEBSITE', 'STATE_ID', 'ALT_NAME', 'ST_FIPS', 'OWNER', 'TTL_STAFF',
       'BEDS', 'TRAUMA', 'HELIPAD'],
      dtype='object')

In [268]:
df_hospitals_brief = df_hospitals[['NAME', 'CITY', 'STATE', 'ZIP', 'COUNTY', 'COUNTYFIPS', 'ST_FIPS']]

In [269]:
hospitals_per_county = df_hospitals['COUNTYFIPS'].value_counts().to_frame()
hospitals_per_county.reset_index(level=0, inplace=True)
hospitals_per_county.rename(index=str, columns={"index": "FIPS", "COUNTYFIPS": "NumberOfHospitals"}, inplace=True)
hospitals_per_county.shape

(2583, 2)

In [270]:
hospitals_per_county['FIPS'] = pd.to_numeric(hospitals_per_county['FIPS'], errors='coerce')

In [271]:
hospitals_per_county_dcmetro = hospitals_per_county.loc[hospitals_per_county['FIPS'].isin(dcmetro_FIPS.values())]

In [272]:
hospitals_per_county_dcmetro

         FIPS  NumberOfHospitals
68    11001.0                 15
149   24031.0                  9
188   51059.0                  8
225   24033.0                  7
397   51107.0                  4
615   51153.0                  3
975   51630.0                  2
1265  51013.0                  1
1445  51683.0                  1
1541  24021.0                  1
1556  54037.0                  1
1601  51177.0                  1
1648  24017.0                  1
1766  51179.0                  1
1842  51510.0                  1
2295  24009.0                  1
2320  51047.0                  1
2406  51061.0                  1
2431  51187.0                  1

In [273]:
len(hospitals_per_county_dcmetro)

19

In [274]:
df_dcmetro_merged = df_dcmetro.merge(schools_per_county_dcmetro, how='left', on='FIPS').merge(hospitals_per_county_dcmetro, how='left', on='FIPS')

In [276]:
df_dcmetro_merged

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2019-06,FIPS,NumberOfSchools,NumberOfHospitals
0,1694,Fairfax County,VA,Washington-Arlington-Alexandria,51,59,36,558783.000000,51059,221,8.0
1,2975,Montgomery County,MD,Washington-Arlington-Alexandria,24,31,42,470224.666667,24031,207,9.0
2,3246,Prince Georges County,MD,Washington-Arlington-Alexandria,24,33,59,312947.333333,24033,214,7.0
3,3289,District of Columbia,DC,Washington-Arlington-Alexandria,11,1,105,623966.666667,11001,249,15.0
4,3247,Prince William County,VA,Washington-Arlington-Alexandria,51,153,165,385136.000000,51153,97,3.0
5,1887,Loudoun County,VA,Washington-Arlington-Alexandria,51,107,203,531570.333333,51107,94,4.0
6,2699,Frederick County,MD,Washington-Arlington-Alexandria,24,21,271,337613.000000,24021,67,1.0
7,2619,Arlington County,VA,Washington-Arlington-Alexandria,51,13,294,711743.333333,51013,39,1.0
8,1607,Charles County,MD,Washington-Arlington-Alexandria,24,17,415,310631.000000,24017,38,1.0
9,3253,Alexandria City,VA,Washington-Arlington-Alexandria,51,510,428,554203.000000,51510,23,1.0
10,2556,Stafford County,VA,Washington-Arlington-Alexandria,51,179,467,347158.333333,51179,32,1.0
11,3193,Spotsylvania County,VA,Washington-Arlington-Alexandria,51,177,482,287085.666667,51177,35,1.0
12,1581,Calvert County,MD,Washington-Arlington-Alexandria,24,9,619,341216.666667,24009,25,1.0
13,2261,Fauquier County,VA,Washington-Arlington-Alexandria,51,61,762,419933.666667,51061,22,1.0
14,2757,Jefferson County,WV,Washington-Arlington-Alexandria,54,37,871,228683.666667,54037,16,1.0
15,2240,Culpeper County,VA,Washington-Arlington-Alexandria,51,47,962,293808.000000,51047,11,1.0
16,3213,Manassas City,VA,Washington-Arlington-Alexandria,51,683,1125,330914.333333,51683,10,1.0
17,1483,Warren County,VA,Washington-Arlington-Alexandria,51,187,1132,223468.333333,51187,8,1.0
18,3283,Fredericksburg City,VA,Washington-Arlington-Alexandria,51,630,1445,325345.333333,51630,6,2.0
19,3162,Fairfax City,VA,Washington-Arlington-Alexandria,51,600,1499,544894.000000,51600,7,NaN
20,943,Clarke County,VA,Washington-Arlington-Alexandria,51,43,1776,358250.000000,51043,4,NaN
21,3272,Falls Church City,VA,Washington-Arlington-Alexandria,51,610,1828,812208.666667,51610,2,NaN