Module-3 project
Title :
Scope of the project :
Members : Mouyo & VJ
Data set:
Stat test:
Hypothesis:
Null Hypothesis:
Assumptions:
Sales price of homes:factors effecting would be preferred area, numb
Preferred areas: Good school ratings, low crime rates,

In [123]:
import pandas as pd

In [124]:
df_schools = pd.read_csv('/Users/vyju/Documents/Module-3 project/Public_Schools.csv')
df.head()

,X,Y,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,ST_GRADE,END_GRADE,DISTRICTID,FT_TEACHER,SHELTER_ID
0,-73.534274,41.327100,1,90381001361,SCOTTS RIDGE MIDDLE SCHOOL,750 NORTH SALEM RD.,RIDGEFIELD,CT,6877,NOT AVAILABLE,...,IMAGERY,2010-03-05T00:00:00.000Z,www.ridgefield.org/srms/index.htm,2,496,06,08,903810,42,10807677
1,-83.002954,42.609035,2,263447007003,BEMIS JUNIOR HIGH SCHOOL,12500 19 MILE RD,STERLING HEIGHTS,MI,48313,2682,...,IMAGERY,2010-08-26T00:00:00.000Z,NOT AVAILABLE,2,943,07,09,2634470,44,NOT AVAILABLE
2,-119.784787,39.509917,3,320048000242,ROGER CORBETT ELEMENTARY SCHOOL,1901 VILLANOVA DRIVE,RENO,NV,89502,NOT AVAILABLE,...,IMAGERY,2010-06-01T00:00:00.000Z,NOT AVAILABLE,1,515,PK,06,3200480,32,NOT AVAILABLE
3,-98.472562,29.436838,4,483312007184,NISD BEXAR COUNTY JJA,1402 HACKBERRY,SAN ANTONIO,TX,78238,1699,...,IMAGERY,2010-02-25T00:00:00.000Z,NOT AVAILABLE,4,25,06,12,4833120,-1,NOT AVAILABLE
4,-95.491060,29.596903,5,481965001816,BRIARGATE EL,15817 BLUE RIDGE RD,MISSOURI CITY,TX,77489,3403,...,IMAGERY,2010-06-21T00:00:00.000Z,www.fortbend.k12.tx.us/campuses/bge/default.cfm,1,468,PK,05,4819650,30,NOT AVAILABLE

In [137]:

df_schools1 = df_schools[['NAME', 'CITY', 'STATE', 'ZIP','COUNTY','COUNTYFIPS', 'DISTRICTID']]

In [138]:
df_schools1.head()

,NAME,CITY,STATE,ZIP,COUNTY,COUNTYFIPS,DISTRICTID
0,SCOTTS RIDGE MIDDLE SCHOOL,RIDGEFIELD,CT,6877,FAIRFIELD,9001,903810
1,BEMIS JUNIOR HIGH SCHOOL,STERLING HEIGHTS,MI,48313,MACOMB,26099,2634470
2,ROGER CORBETT ELEMENTARY SCHOOL,RENO,NV,89502,WASHOE,32031,3200480
3,NISD BEXAR COUNTY JJA,SAN ANTONIO,TX,78238,BEXAR,48029,4833120
4,BRIARGATE EL,MISSOURI CITY,TX,77489,FORT BEND,48157,4819650

In [139]:
df_schools_dcmetro = df_schools1.loc[df_schools['STATE'].isin(['VA', 'DC','MD'])]

In [140]:
df_schools_dcmetro

,NAME,CITY,STATE,ZIP,COUNTY,COUNTYFIPS,DISTRICTID
300,PLAZA MIDDLE,VIRGINIA BEACH,VA,23452,VIRGINIA BEACH,51810,5103840
332,BLAND COUNTY ELEM,BLAND,VA,24315,BLAND,51021,5100390
338,FORESTVILLE ELEM,GREAT FALLS,VA,22066,FAIRFAX,51059,5101260
353,ECOFF ELEM,CHESTER,VA,23831,CHESTERFIELD,51041,5100840
356,ALBERT HARRIS ELEM,MARTINSVILLE,VA,24112,MARTINSVILLE,51690,5102400
...,...,...,...,...,...,...,...
101866,SAMUEL P. LANGLEY ELEM,HAMPTON,VA,23669,HAMPTON,51650,5101800
101908,BERWYN HEIGHTS ELEMENTARY,BERWYN HEIGHTS,MD,20740,PRINCE GEORGE'S,24033,2400510
102158,SALEM MIDDLE,VIRGINIA BEACH,VA,23464,VIRGINIA BEACH,51810,5103840
102170,EDISON HIGH SCHOOL ACADEMY,ALEXANDRIA,VA,22310,FAIRFAX,51059,5101260
102226,BAKER-BUTLER ELEM,CHARLOTTESVILLE,VA,22911,ALBEMARLE,51003,5100090

In [147]:
# Number of Public schools per county
schools_per_county_dcmetro = df_schools_dcmetro['COUNTYFIPS'].value_counts().to_frame()
schools_per_county_dcmetro.reset_index(level=0, inplace=True)
schools_per_county_dcmetro.rename(index=str, columns={"index": "FIPS", "COUNTYFIPS": "NumberOfSchools"}, inplace=True)
schools_per_county_dcmetro.shape

(160, 2)

In [142]:
df_hospitals = pd.read_csv('/Users/vyju/Documents/Module-3 project/Hospitals.csv')
df.head()

,X,Y,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,ST_GRADE,END_GRADE,DISTRICTID,FT_TEACHER,SHELTER_ID
0,-73.534274,41.327100,1,90381001361,SCOTTS RIDGE MIDDLE SCHOOL,750 NORTH SALEM RD.,RIDGEFIELD,CT,6877,NOT AVAILABLE,...,IMAGERY,2010-03-05T00:00:00.000Z,www.ridgefield.org/srms/index.htm,2,496,06,08,903810,42,10807677
1,-83.002954,42.609035,2,263447007003,BEMIS JUNIOR HIGH SCHOOL,12500 19 MILE RD,STERLING HEIGHTS,MI,48313,2682,...,IMAGERY,2010-08-26T00:00:00.000Z,NOT AVAILABLE,2,943,07,09,2634470,44,NOT AVAILABLE
2,-119.784787,39.509917,3,320048000242,ROGER CORBETT ELEMENTARY SCHOOL,1901 VILLANOVA DRIVE,RENO,NV,89502,NOT AVAILABLE,...,IMAGERY,2010-06-01T00:00:00.000Z,NOT AVAILABLE,1,515,PK,06,3200480,32,NOT AVAILABLE
3,-98.472562,29.436838,4,483312007184,NISD BEXAR COUNTY JJA,1402 HACKBERRY,SAN ANTONIO,TX,78238,1699,...,IMAGERY,2010-02-25T00:00:00.000Z,NOT AVAILABLE,4,25,06,12,4833120,-1,NOT AVAILABLE
4,-95.491060,29.596903,5,481965001816,BRIARGATE EL,15817 BLUE RIDGE RD,MISSOURI CITY,TX,77489,3403,...,IMAGERY,2010-06-21T00:00:00.000Z,www.fortbend.k12.tx.us/campuses/bge/default.cfm,1,468,PK,05,4819650,30,NOT AVAILABLE

In [143]:
df_hospitals1 = df_hospitals[['NAME', 'CITY', 'STATE', 'ZIP','COUNTY','COUNTYFIPS', 'ST_FIPS']]

Index(['X', 'Y', 'OBJECTID', 'ID', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP',
       'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'POPULATION', 'COUNTY',
       'COUNTYFIPS', 'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE',
       'NAICS_DESC', 'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE',
       'WEBSITE', 'STATE_ID', 'ALT_NAME', 'ST_FIPS', 'OWNER', 'TTL_STAFF',
       'BEDS', 'TRAUMA', 'HELIPAD'],
      dtype='object')

In [144]:
df_hospitals_dcmetro = df_hospitals1.loc[df_schools['STATE'].isin(['VA', 'DC','MD'])]

In [146]:
# Number of hospitals per county
hospitals_per_county_dcmetro = df_hospitals_dcmetro['COUNTYFIPS'].value_counts().to_frame()
hospitals_per_county_dcmetro.reset_index(level=0, inplace=True)
hospitals_per_county_dcmetro.rename(index=str, columns={"index": "FIPS", "COUNTYFIPS": "NumberOfHospitals"}, inplace=True)
hospitals_per_county_dcmetro.shape

(220, 2)